services:
  - type: web
    name: grindmate
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    envVars:
      - key: VITE_SUPABASE_URL
        sync: false
      - key: VITE_SUPABASE_ANON_KEY
        sync: false
    healthCheckPath: /
    autoDeploy: true
    plan: free
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 